# This is a basic workflow to help you get started with Actions

name: GitGuardian Scan

# Controls when the workflow will run
on:
  push:
    branches:
      - '!main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/workshop-library'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA:  ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }} 
